version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./db.json:/app/db.json
  #   environment:
  #     - NODE_ENV=development
